[package]
name = "Rust-Calc"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.0", features = ["wgpu"] }

[[bin]]
name = "rust-calc"  # This will produce "rust-calc.exe"
path = "src/main.rs"